const i = (item, quantity, unit, category) => ({ item, quantity, unit, category });

export const extraRecipes = [
  {
    id: 'crispy-greek-filo-pie',
    title: 'Crispy Greek Filo Pie',
    description: 'A crisp filo pie packed with feta, spinach, herbs and lemon.',
    servings: 4,
    protein: 'Vegetarian',
    cuisine: 'Mediterranean',
    timeMinutes: 55,
    calories: 620,
    difficulty: 'Medium',
    familyFriendly: true,
    tags: ['vegetarian', 'comfort-food', 'weekend-cooking', 'family-friendly'],
    ingredients: [i('filo pastry', 270, 'g', 'Carbs'), i('feta', 250, 'g', 'Dairy'), i('spinach', 300, 'g', 'Fruit & veg'), i('eggs', 3, '', 'Dairy'), i('spring onions', 1, 'bunch', 'Fruit & veg'), i('dill', 1, 'bunch', 'Fruit & veg'), i('lemon', 1, '', 'Fruit & veg'), i('olive oil', 2, 'tbsp', 'Herbs, spices & sauces')],
    method: ['Wilt the spinach, squeeze out excess water and chop.', 'Mix spinach with feta, eggs, spring onions, dill, lemon zest and black pepper.', 'Layer filo sheets in an oiled tin, brushing lightly with oil.', 'Add the filling and fold the filo over the top.', 'Bake until deeply golden and crisp.']
  },
  {
    id: 'chicken-stroganoff',
    title: 'Chicken Stroganoff',
    description: 'Creamy paprika chicken with mushrooms, rice and a lighter yoghurt finish.',
    servings: 4,
    protein: 'Chicken',
    cuisine: 'European',
    timeMinutes: 35,
    calories: 610,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['quick', 'comfort-food', 'high-protein', 'family-friendly'],
    ingredients: [i('chicken breast', 650, 'g', 'Meat & fish'), i('mushrooms', 300, 'g', 'Fruit & veg'), i('onion', 1, '', 'Fruit & veg'), i('garlic', 2, 'cloves', 'Fruit & veg'), i('paprika', 2, 'tsp', 'Herbs, spices & sauces'), i('chicken stock', 300, 'ml', 'Tins, jars & packets'), i('Greek yoghurt', 150, 'g', 'Dairy'), i('rice', 300, 'g', 'Carbs')],
    method: ['Cook the rice.', 'Brown sliced chicken in a wide pan and set aside.', 'Cook onion, mushrooms and garlic until softened.', 'Stir in paprika, stock and chicken.', 'Simmer until cooked through, then turn off the heat and stir in yoghurt.']
  },
  {
    id: 'pork-and-bean-cassoulet',
    title: 'Pork and Bean Cassoulet',
    description: 'A hearty pork, sausage and bean bake with a crisp herby crumb.',
    servings: 4,
    protein: 'Pork',
    cuisine: 'French',
    timeMinutes: 65,
    calories: 720,
    difficulty: 'Medium',
    familyFriendly: true,
    tags: ['comfort-food', 'batch-cook', 'winter', 'weekend-cooking'],
    ingredients: [i('pork shoulder steaks', 500, 'g', 'Meat & fish'), i('sausages', 4, '', 'Meat & fish'), i('cannellini beans', 2, 'tins', 'Tins, jars & packets'), i('tinned tomatoes', 1, 'tin', 'Tins, jars & packets'), i('onion', 1, '', 'Fruit & veg'), i('carrot', 2, '', 'Fruit & veg'), i('garlic', 3, 'cloves', 'Fruit & veg'), i('breadcrumbs', 60, 'g', 'Carbs')],
    method: ['Brown pork pieces and sausages in a casserole pan.', 'Add onion, carrot and garlic and cook until softened.', 'Stir in tomatoes, beans and a splash of stock or water.', 'Simmer until the pork is tender.', 'Top with breadcrumbs and bake until crisp.']
  },
  {
    id: 'marrakech-beef-chilli',
    title: 'Marrakech Beef Chilli',
    description: 'A warm Moroccan-style chilli with beef, chickpeas, apricots and spice.',
    servings: 4,
    protein: 'Beef',
    cuisine: 'Middle Eastern',
    timeMinutes: 50,
    calories: 650,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['batch-cook', 'comfort-food', 'high-protein', 'freezer-friendly'],
    ingredients: [i('lean beef mince', 500, 'g', 'Meat & fish'), i('chickpeas', 1, 'tin', 'Tins, jars & packets'), i('tinned tomatoes', 2, 'tins', 'Tins, jars & packets'), i('onion', 1, '', 'Fruit & veg'), i('ras el hanout', 2, 'tbsp', 'Herbs, spices & sauces'), i('dried apricots', 80, 'g', 'Tins, jars & packets'), i('couscous', 280, 'g', 'Carbs'), i('Greek yoghurt', 120, 'g', 'Dairy')],
    method: ['Brown the beef mince with onion.', 'Add ras el hanout and cook for a minute.', 'Add tomatoes, chickpeas and chopped apricots.', 'Simmer until thick and rich.', 'Serve with couscous and yoghurt.']
  },
  {
    id: 'berbere-chicken-potato-traybake',
    title: 'Berbere Chicken, Potato and Greens Traybake',
    description: 'Spiced chicken thighs roasted with potatoes and finished with greens.',
    servings: 4,
    protein: 'Chicken',
    cuisine: 'African-inspired',
    timeMinutes: 55,
    calories: 620,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['one-pan', 'high-protein', 'weeknight', 'spicy'],
    ingredients: [i('chicken thighs', 800, 'g', 'Meat & fish'), i('potatoes', 800, 'g', 'Carbs'), i('red onion', 2, '', 'Fruit & veg'), i('berbere spice', 2, 'tbsp', 'Herbs, spices & sauces'), i('olive oil', 1, 'tbsp', 'Herbs, spices & sauces'), i('spring greens', 250, 'g', 'Fruit & veg'), i('lemon', 1, '', 'Fruit & veg')],
    method: ['Toss chicken, potato chunks and onion with berbere, oil and salt.', 'Roast until the potatoes are golden and chicken is cooked.', 'Add chopped greens for the final few minutes.', 'Finish with lemon juice and serve.']
  },
  {
    id: 'sweet-chilli-peanut-chicken-noodle-salad',
    title: 'Sweet Chilli Peanut Chicken Noodle Salad',
    description: 'Cold noodle salad with chicken, crunchy veg, peanuts and a sweet chilli dressing.',
    servings: 4,
    protein: 'Chicken',
    cuisine: 'Asian',
    timeMinutes: 25,
    calories: 580,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['quick', 'summer', 'high-protein', 'packed-lunch'],
    ingredients: [i('cooked chicken', 500, 'g', 'Meat & fish'), i('rice noodles', 250, 'g', 'Carbs'), i('cucumber', 1, '', 'Fruit & veg'), i('carrot', 2, '', 'Fruit & veg'), i('red pepper', 1, '', 'Fruit & veg'), i('sweet chilli sauce', 4, 'tbsp', 'Herbs, spices & sauces'), i('peanut butter', 2, 'tbsp', 'Tins, jars & packets'), i('peanuts', 50, 'g', 'Tins, jars & packets')],
    method: ['Cook and cool the noodles.', 'Shred the chicken and slice the vegetables.', 'Whisk sweet chilli sauce with peanut butter, lime or water to loosen.', 'Toss everything together.', 'Top with chopped peanuts.']
  },
  {
    id: 'hidden-veg-tomato-pasta',
    title: 'Hidden Veg Tomato Pasta',
    description: 'A smooth tomato pasta sauce packed with blended vegetables.',
    servings: 4,
    protein: 'Vegetarian',
    cuisine: 'Italian',
    timeMinutes: 40,
    calories: 520,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['family-friendly', 'vegetarian', 'batch-cook', 'freezer-friendly'],
    ingredients: [i('pasta', 350, 'g', 'Carbs'), i('passata', 500, 'g', 'Tins, jars & packets'), i('courgette', 1, '', 'Fruit & veg'), i('carrot', 2, '', 'Fruit & veg'), i('red pepper', 1, '', 'Fruit & veg'), i('onion', 1, '', 'Fruit & veg'), i('garlic', 2, 'cloves', 'Fruit & veg'), i('cheddar', 60, 'g', 'Dairy')],
    method: ['Soften the chopped vegetables with onion and garlic.', 'Add passata and simmer until everything is tender.', 'Blend until smooth.', 'Cook pasta and toss with the sauce.', 'Finish with grated cheese.']
  },
  {
    id: 'cheesy-tomato-gnocchi-bake',
    title: 'Cheesy Tomato Gnocchi Bake',
    description: 'Soft gnocchi baked in tomato sauce with mozzarella and basil.',
    servings: 4,
    protein: 'Vegetarian',
    cuisine: 'Italian',
    timeMinutes: 30,
    calories: 650,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['quick', 'vegetarian', 'comfort-food', 'one-pan'],
    ingredients: [i('gnocchi', 700, 'g', 'Carbs'), i('passata', 500, 'g', 'Tins, jars & packets'), i('cherry tomatoes', 250, 'g', 'Fruit & veg'), i('garlic', 2, 'cloves', 'Fruit & veg'), i('mozzarella', 250, 'g', 'Dairy'), i('parmesan', 30, 'g', 'Dairy'), i('basil', 1, 'bunch', 'Fruit & veg')],
    method: ['Simmer passata with garlic and cherry tomatoes.', 'Stir in gnocchi and a splash of water.', 'Top with mozzarella and parmesan.', 'Bake until bubbling and golden.', 'Scatter with basil.']
  },
  {
    id: 'hot-honey-baked-feta',
    title: 'Hot Honey Baked Feta with Tomatoes',
    description: 'Baked feta with burst tomatoes, chilli, herbs and honey.',
    servings: 4,
    protein: 'Vegetarian',
    cuisine: 'Mediterranean',
    timeMinutes: 30,
    calories: 520,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['vegetarian', 'summer', 'sharing', 'quick'],
    ingredients: [i('feta', 400, 'g', 'Dairy'), i('cherry tomatoes', 500, 'g', 'Fruit & veg'), i('red onion', 1, '', 'Fruit & veg'), i('honey', 2, 'tbsp', 'Tins, jars & packets'), i('chilli flakes', 1, 'tsp', 'Herbs, spices & sauces'), i('olive oil', 1, 'tbsp', 'Herbs, spices & sauces'), i('flatbreads', 4, '', 'Carbs')],
    method: ['Put feta, tomatoes and sliced onion in a baking dish.', 'Drizzle with oil, honey and chilli.', 'Bake until the feta softens and tomatoes burst.', 'Serve with warm flatbreads and salad.']
  },
  {
    id: 'slow-cooker-bbq-pulled-pork',
    title: 'Slow Cooker BBQ Pulled Pork',
    description: 'Tender shredded pork in a smoky BBQ sauce for buns, bowls or loaded potatoes.',
    servings: 6,
    protein: 'Pork',
    cuisine: 'American',
    timeMinutes: 480,
    calories: 590,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['slow-cooker', 'batch-cook', 'fakeaway', 'family-friendly'],
    ingredients: [i('pork shoulder', 1200, 'g', 'Meat & fish'), i('BBQ sauce', 250, 'ml', 'Herbs, spices & sauces'), i('onion', 1, '', 'Fruit & veg'), i('smoked paprika', 2, 'tsp', 'Herbs, spices & sauces'), i('brown sugar', 1, 'tbsp', 'Tins, jars & packets'), i('apple cider vinegar', 2, 'tbsp', 'Herbs, spices & sauces'), i('burger buns', 6, '', 'Carbs')],
    method: ['Put sliced onion in the slow cooker.', 'Rub pork with paprika, sugar, salt and pepper.', 'Add BBQ sauce and vinegar.', 'Cook on low until the pork shreds easily.', 'Shred and serve in buns.']
  },
  {
    id: 'simple-coq-au-vin',
    title: 'Simple Coq au Vin',
    description: 'Chicken braised with mushrooms, bacon, herbs and red wine-style richness.',
    servings: 4,
    protein: 'Chicken',
    cuisine: 'French',
    timeMinutes: 75,
    calories: 680,
    difficulty: 'Medium',
    familyFriendly: true,
    tags: ['comfort-food', 'weekend-cooking', 'high-protein', 'winter'],
    ingredients: [i('chicken thighs', 800, 'g', 'Meat & fish'), i('bacon lardons', 150, 'g', 'Meat & fish'), i('mushrooms', 250, 'g', 'Fruit & veg'), i('shallots', 8, '', 'Fruit & veg'), i('garlic', 3, 'cloves', 'Fruit & veg'), i('red wine stock pot', 1, '', 'Tins, jars & packets'), i('chicken stock', 400, 'ml', 'Tins, jars & packets'), i('mashed potatoes', 800, 'g', 'Carbs')],
    method: ['Brown chicken and bacon in a casserole.', 'Add shallots, mushrooms and garlic.', 'Stir in stock and red wine stock pot.', 'Simmer until chicken is tender and sauce is glossy.', 'Serve with mash.']
  },
  {
    id: 'french-chicken-peas-bacon',
    title: 'French Chicken with Peas and Bacon',
    description: 'Creamy mustard chicken with peas, bacon and potatoes.',
    servings: 4,
    protein: 'Chicken',
    cuisine: 'French',
    timeMinutes: 40,
    calories: 640,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['weeknight', 'high-protein', 'comfort-food', 'one-pan'],
    ingredients: [i('chicken thighs', 700, 'g', 'Meat & fish'), i('bacon lardons', 120, 'g', 'Meat & fish'), i('peas', 250, 'g', 'Frozen'), i('baby potatoes', 700, 'g', 'Carbs'), i('wholegrain mustard', 2, 'tbsp', 'Herbs, spices & sauces'), i('chicken stock', 300, 'ml', 'Tins, jars & packets'), i('creme fraiche', 120, 'g', 'Dairy')],
    method: ['Brown chicken and bacon.', 'Add potatoes, mustard and stock.', 'Simmer until potatoes and chicken are cooked.', 'Stir in peas and creme fraiche.', 'Serve with black pepper.']
  },
  {
    id: 'crispy-chilli-chicken-traybake',
    title: 'Crispy Chilli Chicken Traybake',
    description: 'Crispy oven chicken with sticky chilli glaze, peppers and rice.',
    servings: 4,
    protein: 'Chicken',
    cuisine: 'Asian',
    timeMinutes: 45,
    calories: 670,
    difficulty: 'Medium',
    familyFriendly: true,
    tags: ['fakeaway', 'high-protein', 'spicy', 'one-pan'],
    ingredients: [i('chicken thighs', 750, 'g', 'Meat & fish'), i('cornflour', 4, 'tbsp', 'Tins, jars & packets'), i('sweet chilli sauce', 5, 'tbsp', 'Herbs, spices & sauces'), i('soy sauce', 2, 'tbsp', 'Herbs, spices & sauces'), i('mixed peppers', 3, '', 'Fruit & veg'), i('spring onions', 1, 'bunch', 'Fruit & veg'), i('rice', 300, 'g', 'Carbs')],
    method: ['Coat chicken pieces in seasoned cornflour.', 'Bake on a hot tray until crisp.', 'Add sliced peppers partway through.', 'Toss chicken with sweet chilli and soy.', 'Serve with rice and spring onions.']
  },
  {
    id: 'lamb-boulangere',
    title: 'Roast Lamb with Boulangere Potatoes',
    description: 'Slow roast lamb served with layered potatoes and onions.',
    servings: 6,
    protein: 'Lamb',
    cuisine: 'French',
    timeMinutes: 130,
    calories: 760,
    difficulty: 'Medium',
    familyFriendly: true,
    tags: ['weekend-cooking', 'comfort-food', 'sunday-dinner', 'high-protein'],
    ingredients: [i('lamb shoulder', 1200, 'g', 'Meat & fish'), i('potatoes', 1200, 'g', 'Carbs'), i('onions', 3, '', 'Fruit & veg'), i('lamb stock', 500, 'ml', 'Tins, jars & packets'), i('rosemary', 2, 'tsp', 'Herbs, spices & sauces'), i('garlic', 4, 'cloves', 'Fruit & veg'), i('green beans', 400, 'g', 'Fruit & veg')],
    method: ['Layer thin potato and onion slices in a roasting dish.', 'Pour over stock and herbs.', 'Rub lamb with garlic, rosemary, salt and pepper.', 'Roast lamb above or beside the potatoes until tender.', 'Rest, carve and serve with green beans.']
  },
  {
    id: 'honey-soy-chicken-sesame-broccoli',
    title: 'Honey Soy Chicken with Sesame Broccoli',
    description: 'Sticky chicken thighs with garlicky broccoli and rice.',
    servings: 4,
    protein: 'Chicken',
    cuisine: 'Asian',
    timeMinutes: 35,
    calories: 610,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['quick', 'high-protein', 'weeknight', 'fakeaway'],
    ingredients: [i('chicken thighs', 750, 'g', 'Meat & fish'), i('soy sauce', 4, 'tbsp', 'Herbs, spices & sauces'), i('honey', 2, 'tbsp', 'Tins, jars & packets'), i('garlic', 3, 'cloves', 'Fruit & veg'), i('broccoli', 2, 'heads', 'Fruit & veg'), i('sesame seeds', 2, 'tbsp', 'Tins, jars & packets'), i('rice', 300, 'g', 'Carbs')],
    method: ['Cook rice.', 'Mix soy, honey and garlic.', 'Pan-fry chicken until cooked and sticky.', 'Steam or stir-fry broccoli.', 'Serve with sesame seeds and rice.']
  },
  {
    id: 'grana-schnitzel-sandwich',
    title: 'Crispy Parmesan Chicken Schnitzel Sandwich',
    description: 'Crispy cheesy chicken in toasted ciabatta with lemony mayo and salad.',
    servings: 4,
    protein: 'Chicken',
    cuisine: 'Italian',
    timeMinutes: 35,
    calories: 720,
    difficulty: 'Medium',
    familyFriendly: true,
    tags: ['fakeaway', 'weekend-cooking', 'high-protein', 'family-friendly'],
    ingredients: [i('chicken breast', 650, 'g', 'Meat & fish'), i('breadcrumbs', 120, 'g', 'Carbs'), i('parmesan', 60, 'g', 'Dairy'), i('eggs', 2, '', 'Dairy'), i('ciabatta rolls', 4, '', 'Carbs'), i('lettuce', 1, 'bag', 'Fruit & veg'), i('mayonnaise', 4, 'tbsp', 'Herbs, spices & sauces'), i('lemon', 1, '', 'Fruit & veg')],
    method: ['Flatten chicken breasts into thin pieces.', 'Dip in egg, then breadcrumbs mixed with parmesan.', 'Fry or bake until crisp and cooked through.', 'Mix mayo with lemon.', 'Serve in toasted rolls with lettuce.']
  },
  {
    id: 'goats-cheese-spinach-filo-pie',
    title: 'Goat Cheese, Spinach and Onion Filo Pie',
    description: 'Crisp filo with caramelised onions, spinach and tangy goat cheese.',
    servings: 4,
    protein: 'Vegetarian',
    cuisine: 'Mediterranean',
    timeMinutes: 60,
    calories: 640,
    difficulty: 'Medium',
    familyFriendly: true,
    tags: ['vegetarian', 'comfort-food', 'weekend-cooking', 'summer'],
    ingredients: [i('filo pastry', 270, 'g', 'Carbs'), i('goat cheese', 200, 'g', 'Dairy'), i('spinach', 300, 'g', 'Fruit & veg'), i('red onions', 3, '', 'Fruit & veg'), i('eggs', 3, '', 'Dairy'), i('thyme', 2, 'tsp', 'Herbs, spices & sauces'), i('olive oil', 2, 'tbsp', 'Herbs, spices & sauces')],
    method: ['Slowly cook onions until soft and sweet.', 'Wilt spinach and squeeze dry.', 'Mix spinach, onions, eggs and crumbled goat cheese.', 'Layer filo in a tin and add filling.', 'Bake until golden and crisp.']
  },
  {
    id: 'chicken-provencal-garlic-potatoes',
    title: 'Chicken Provencal with Sticky Garlic Potatoes',
    description: 'Tomato, olive and herb chicken with golden garlic potatoes.',
    servings: 4,
    protein: 'Chicken',
    cuisine: 'Mediterranean',
    timeMinutes: 60,
    calories: 680,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['one-pan', 'high-protein', 'summer', 'comfort-food'],
    ingredients: [i('chicken thighs', 800, 'g', 'Meat & fish'), i('baby potatoes', 800, 'g', 'Carbs'), i('cherry tomatoes', 400, 'g', 'Fruit & veg'), i('olives', 100, 'g', 'Tins, jars & packets'), i('garlic', 6, 'cloves', 'Fruit & veg'), i('Italian herbs', 2, 'tsp', 'Herbs, spices & sauces'), i('lemon', 1, '', 'Fruit & veg')],
    method: ['Roast potatoes with garlic until starting to crisp.', 'Add chicken, tomatoes, olives and herbs.', 'Roast until chicken is cooked and tomatoes are jammy.', 'Finish with lemon juice.']
  },
  {
    id: 'homemade-rotisserie-chicken',
    title: 'Homemade Rotisserie-Style Chicken',
    description: 'Juicy roast chicken with paprika, garlic and lemon-herb seasoning.',
    servings: 4,
    protein: 'Chicken',
    cuisine: 'British',
    timeMinutes: 90,
    calories: 620,
    difficulty: 'Medium',
    familyFriendly: true,
    tags: ['sunday-dinner', 'high-protein', 'batch-cook', 'family-friendly'],
    ingredients: [i('whole chicken', 1500, 'g', 'Meat & fish'), i('paprika', 2, 'tsp', 'Herbs, spices & sauces'), i('garlic powder', 1, 'tsp', 'Herbs, spices & sauces'), i('lemon', 1, '', 'Fruit & veg'), i('butter', 40, 'g', 'Dairy'), i('potatoes', 800, 'g', 'Carbs'), i('mixed salad', 1, 'bag', 'Fruit & veg')],
    method: ['Mix butter with paprika, garlic powder, salt and pepper.', 'Rub over the chicken and stuff lemon inside.', 'Roast until golden and cooked through.', 'Rest before carving.', 'Serve with potatoes and salad.']
  },
  {
    id: 'creamy-tuscan-bean-skillet',
    title: 'Creamy Tuscan Bean and Sun-Dried Tomato Skillet',
    description: 'Creamy cannellini beans with sun-dried tomatoes, spinach and parmesan.',
    servings: 4,
    protein: 'Vegetarian',
    cuisine: 'Italian',
    timeMinutes: 25,
    calories: 540,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['quick', 'vegetarian', 'one-pan', 'high-fibre'],
    ingredients: [i('cannellini beans', 3, 'tins', 'Tins, jars & packets'), i('sun-dried tomatoes', 120, 'g', 'Tins, jars & packets'), i('spinach', 200, 'g', 'Fruit & veg'), i('garlic', 3, 'cloves', 'Fruit & veg'), i('cream cheese', 120, 'g', 'Dairy'), i('parmesan', 40, 'g', 'Dairy'), i('crusty bread', 1, 'loaf', 'Carbs')],
    method: ['Cook garlic and chopped sun-dried tomatoes in a pan.', 'Add beans and a splash of water or stock.', 'Stir in cream cheese and parmesan.', 'Fold through spinach until wilted.', 'Serve with crusty bread.']
  },
  {
    id: 'chipotle-chicken-polenta',
    title: 'Crispy Chipotle Chicken with Cheesy Polenta',
    description: 'Smoky crisp chicken served over creamy cheesy polenta with jalapeno jam.',
    servings: 4,
    protein: 'Chicken',
    cuisine: 'Mexican',
    timeMinutes: 45,
    calories: 720,
    difficulty: 'Medium',
    familyFriendly: true,
    tags: ['fakeaway', 'spicy', 'high-protein', 'weekend-cooking'],
    ingredients: [i('chicken breast', 650, 'g', 'Meat & fish'), i('chipotle paste', 2, 'tbsp', 'Herbs, spices & sauces'), i('breadcrumbs', 100, 'g', 'Carbs'), i('polenta', 180, 'g', 'Carbs'), i('cheddar', 80, 'g', 'Dairy'), i('jalapenos', 60, 'g', 'Tins, jars & packets'), i('honey', 1, 'tbsp', 'Tins, jars & packets')],
    method: ['Coat chicken in chipotle paste and breadcrumbs.', 'Bake or fry until crisp and cooked.', 'Cook polenta until thick and creamy.', 'Stir cheese into the polenta.', 'Warm jalapenos with honey and spoon over the chicken.']
  },
  {
    id: 'korean-honey-sesame-chicken',
    title: 'Korean Chilli, Sesame and Honey Chicken',
    description: 'Sticky Korean-style chicken with sesame, rice and crunchy cucumber.',
    servings: 4,
    protein: 'Chicken',
    cuisine: 'Korean',
    timeMinutes: 35,
    calories: 640,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['fakeaway', 'high-protein', 'spicy', 'weeknight'],
    ingredients: [i('chicken thighs', 750, 'g', 'Meat & fish'), i('gochujang', 2, 'tbsp', 'Herbs, spices & sauces'), i('honey', 2, 'tbsp', 'Tins, jars & packets'), i('soy sauce', 3, 'tbsp', 'Herbs, spices & sauces'), i('sesame seeds', 2, 'tbsp', 'Tins, jars & packets'), i('rice', 300, 'g', 'Carbs'), i('cucumber', 1, '', 'Fruit & veg')],
    method: ['Mix gochujang, honey and soy.', 'Fry or roast chicken until nearly cooked.', 'Brush with sauce and cook until sticky.', 'Serve with rice, cucumber and sesame seeds.']
  },
  {
    id: 'chicken-chow-mein',
    title: 'Chicken Chow Mein',
    description: 'A quick fakeaway noodle stir-fry with chicken, veg and soy sauce.',
    servings: 4,
    protein: 'Chicken',
    cuisine: 'Chinese',
    timeMinutes: 25,
    calories: 560,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['quick', 'fakeaway', 'high-protein', 'weeknight'],
    ingredients: [i('chicken breast', 550, 'g', 'Meat & fish'), i('egg noodles', 350, 'g', 'Carbs'), i('stir-fry vegetables', 500, 'g', 'Fruit & veg'), i('soy sauce', 4, 'tbsp', 'Herbs, spices & sauces'), i('oyster sauce', 2, 'tbsp', 'Herbs, spices & sauces'), i('garlic', 2, 'cloves', 'Fruit & veg'), i('spring onions', 1, 'bunch', 'Fruit & veg')],
    method: ['Cook noodles and drain.', 'Stir-fry sliced chicken until cooked.', 'Add vegetables and garlic.', 'Toss through noodles, soy and oyster sauce.', 'Finish with spring onions.']
  },
  {
    id: 'crispy-chilli-beef',
    title: 'Crispy Chilli Beef',
    description: 'Crispy beef strips in a sweet, sticky chilli sauce with rice.',
    servings: 4,
    protein: 'Beef',
    cuisine: 'Chinese',
    timeMinutes: 35,
    calories: 690,
    difficulty: 'Medium',
    familyFriendly: true,
    tags: ['fakeaway', 'spicy', 'high-protein', 'weekend-cooking'],
    ingredients: [i('steak strips', 550, 'g', 'Meat & fish'), i('cornflour', 5, 'tbsp', 'Tins, jars & packets'), i('sweet chilli sauce', 5, 'tbsp', 'Herbs, spices & sauces'), i('soy sauce', 2, 'tbsp', 'Herbs, spices & sauces'), i('red pepper', 1, '', 'Fruit & veg'), i('carrot', 2, '', 'Fruit & veg'), i('rice', 300, 'g', 'Carbs')],
    method: ['Coat beef strips in seasoned cornflour.', 'Fry or air-fry until crisp.', 'Stir-fry pepper and carrot.', 'Toss beef with sweet chilli and soy.', 'Serve with rice.']
  },
  {
    id: 'steak-tagliatelle',
    title: 'Steak Tagliatelle',
    description: 'Sliced steak with tagliatelle, mushrooms, rocket and parmesan.',
    servings: 4,
    protein: 'Beef',
    cuisine: 'Italian',
    timeMinutes: 30,
    calories: 690,
    difficulty: 'Medium',
    familyFriendly: true,
    tags: ['quick', 'high-protein', 'date-night', 'weekend-cooking'],
    ingredients: [i('steak', 600, 'g', 'Meat & fish'), i('tagliatelle', 350, 'g', 'Carbs'), i('mushrooms', 250, 'g', 'Fruit & veg'), i('garlic', 3, 'cloves', 'Fruit & veg'), i('rocket', 1, 'bag', 'Fruit & veg'), i('parmesan', 50, 'g', 'Dairy'), i('creme fraiche', 120, 'g', 'Dairy')],
    method: ['Cook tagliatelle.', 'Cook steak to your liking and rest.', 'Fry mushrooms and garlic.', 'Stir in creme fraiche and pasta water.', 'Toss with pasta and top with sliced steak, rocket and parmesan.']
  },
  {
    id: 'cheese-and-onion-pie',
    title: 'Firm Cheese and Onion Pie',
    description: 'A savoury, firm-set cheese and onion pie that is rich but not sloppy.',
    servings: 6,
    protein: 'Vegetarian',
    cuisine: 'British',
    timeMinutes: 80,
    calories: 640,
    difficulty: 'Medium',
    familyFriendly: true,
    tags: ['comfort-food', 'vegetarian', 'weekend-cooking', 'family-friendly'],
    ingredients: [i('shortcrust pastry', 500, 'g', 'Carbs'), i('mature cheddar', 300, 'g', 'Dairy'), i('onions', 4, '', 'Fruit & veg'), i('eggs', 3, '', 'Dairy'), i('cream cheese', 100, 'g', 'Dairy'), i('mustard powder', 1, 'tsp', 'Herbs, spices & sauces'), i('potatoes', 900, 'g', 'Carbs')],
    method: ['Slowly cook onions until soft and golden, then cool.', 'Mix cheddar, eggs, cream cheese, mustard powder and onions.', 'Line a pie dish with pastry and add filling.', 'Top with pastry and seal.', 'Bake until golden and set, then rest before slicing.']
  },
  {
    id: 'garlic-tomato-cheese-pizza-bread',
    title: 'Punchy Garlic Tomato Cheese Pizza Bread',
    description: 'Pizza dough topped with garlic oil, tomato, mozzarella and hard cheese.',
    servings: 4,
    protein: 'Vegetarian',
    cuisine: 'Italian',
    timeMinutes: 25,
    calories: 560,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['pizza-night', 'vegetarian', 'sharing', 'fakeaway'],
    ingredients: [i('pizza dough', 500, 'g', 'Carbs'), i('passata', 150, 'g', 'Tins, jars & packets'), i('garlic', 5, 'cloves', 'Fruit & veg'), i('mozzarella', 200, 'g', 'Dairy'), i('parmesan', 40, 'g', 'Dairy'), i('basil', 1, 'bunch', 'Fruit & veg'), i('olive oil', 2, 'tbsp', 'Herbs, spices & sauces')],
    method: ['Heat a pizza steel or tray until very hot.', 'Mix crushed garlic with olive oil.', 'Stretch the dough and spread lightly with passata.', 'Add garlic oil, mozzarella and parmesan.', 'Bake until blistered and finish with basil.']
  },
  {
    id: 'thai-chicken-noodle-soup',
    title: 'Thai-Style Chicken Noodle Soup',
    description: 'Fragrant chicken broth with noodles, lime, ginger, chilli and herbs.',
    servings: 4,
    protein: 'Chicken',
    cuisine: 'Thai',
    timeMinutes: 35,
    calories: 510,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['quick', 'high-protein', 'comfort-food', 'lighter'],
    ingredients: [i('chicken thighs', 650, 'g', 'Meat & fish'), i('chicken stock', 1.2, 'litres', 'Tins, jars & packets'), i('rice noodles', 250, 'g', 'Carbs'), i('ginger', 1, 'thumb', 'Fruit & veg'), i('garlic', 3, 'cloves', 'Fruit & veg'), i('lime', 2, '', 'Fruit & veg'), i('coriander', 1, 'bunch', 'Fruit & veg'), i('fish sauce', 2, 'tbsp', 'Herbs, spices & sauces')],
    method: ['Simmer chicken in stock with ginger and garlic.', 'Shred the cooked chicken.', 'Add noodles and cook until tender.', 'Season with lime and fish sauce.', 'Finish with coriander and chilli if liked.']
  },
  {
    id: 'popl-style-smash-burgers',
    title: 'Aged Beef Smash Burgers',
    description: 'Juicy homemade smash burgers with pickles, sauce and soft buns.',
    servings: 5,
    protein: 'Beef',
    cuisine: 'American',
    timeMinutes: 35,
    calories: 760,
    difficulty: 'Medium',
    familyFriendly: true,
    tags: ['fakeaway', 'weekend-cooking', 'high-protein', 'family-friendly'],
    ingredients: [i('beef mince', 1000, 'g', 'Meat & fish'), i('burger buns', 5, '', 'Carbs'), i('cheese slices', 5, '', 'Dairy'), i('pickles', 1, 'jar', 'Tins, jars & packets'), i('lettuce', 1, 'bag', 'Fruit & veg'), i('mayonnaise', 4, 'tbsp', 'Herbs, spices & sauces'), i('ketchup', 2, 'tbsp', 'Herbs, spices & sauces')],
    method: ['Shape mince into loose balls and season well.', 'Smash onto a very hot pan or griddle.', 'Cook until crusted, then flip and add cheese.', 'Toast buns and mix mayo with ketchup.', 'Build with sauce, lettuce and pickles.']
  },
  {
    id: 'cast-iron-harissa-chicken',
    title: 'Cast Iron Harissa Chicken with Lemon Yoghurt',
    description: 'Charred harissa chicken with courgettes and cooling lemon yoghurt.',
    servings: 4,
    protein: 'Chicken',
    cuisine: 'Middle Eastern',
    timeMinutes: 40,
    calories: 590,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['high-protein', 'one-pan', 'spicy', 'weeknight'],
    ingredients: [i('chicken thighs', 750, 'g', 'Meat & fish'), i('harissa paste', 2, 'tbsp', 'Herbs, spices & sauces'), i('courgettes', 3, '', 'Fruit & veg'), i('Greek yoghurt', 180, 'g', 'Dairy'), i('lemon', 1, '', 'Fruit & veg'), i('couscous', 280, 'g', 'Carbs'), i('mint', 1, 'bunch', 'Fruit & veg')],
    method: ['Coat chicken in harissa and a little oil.', 'Sear in cast iron until coloured, then finish in the oven.', 'Char courgettes in the same pan.', 'Mix yoghurt with lemon and mint.', 'Serve with couscous.']
  },
  {
    id: 'baked-feta-lamb-kofta-platter',
    title: 'Baked Feta and Lamb Kofta Platter',
    description: 'A summery platter with lamb koftas, baked feta, olives and courgettes.',
    servings: 4,
    protein: 'Lamb',
    cuisine: 'Mediterranean',
    timeMinutes: 45,
    calories: 720,
    difficulty: 'Medium',
    familyFriendly: true,
    tags: ['sharing', 'summer', 'high-protein', 'weekend-cooking'],
    ingredients: [i('lamb mince', 500, 'g', 'Meat & fish'), i('feta', 300, 'g', 'Dairy'), i('cherry tomatoes', 400, 'g', 'Fruit & veg'), i('courgettes', 3, '', 'Fruit & veg'), i('olives', 100, 'g', 'Tins, jars & packets'), i('flatbreads', 4, '', 'Carbs'), i('cumin', 2, 'tsp', 'Herbs, spices & sauces')],
    method: ['Shape lamb mince with cumin, salt and pepper into koftas.', 'Bake feta with tomatoes and olives.', 'Char courgettes in a hot pan.', 'Cook koftas until browned and cooked through.', 'Serve everything with warm flatbreads.']
  },
  {
    id: 'semolina-chicken-tenders-caesar',
    title: 'Semolina Chicken Tenders with Lighter Caesar Salad',
    description: 'Crunchy oven chicken tenders with a tangy yoghurt Caesar salad.',
    servings: 4,
    protein: 'Chicken',
    cuisine: 'British',
    timeMinutes: 35,
    calories: 560,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['high-protein', 'family-friendly', 'lighter', 'weeknight'],
    ingredients: [i('chicken mini fillets', 650, 'g', 'Meat & fish'), i('semolina', 80, 'g', 'Carbs'), i('romaine lettuce', 2, 'heads', 'Fruit & veg'), i('Greek yoghurt', 160, 'g', 'Dairy'), i('parmesan', 50, 'g', 'Dairy'), i('lemon', 1, '', 'Fruit & veg'), i('capers', 2, 'tbsp', 'Tins, jars & packets')],
    method: ['Coat chicken in seasoned semolina.', 'Bake or air-fry until crisp and cooked.', 'Mix yoghurt, parmesan, lemon and chopped capers.', 'Toss lettuce with dressing.', 'Serve chicken over the salad.']
  },
  {
    id: 'courgette-harissa-lemon-yoghurt',
    title: 'Charred Courgettes with Harissa and Lemon Yoghurt',
    description: 'A light hot lunch or side with smoky courgettes and cooling yoghurt.',
    servings: 2,
    protein: 'Vegetarian',
    cuisine: 'Middle Eastern',
    timeMinutes: 25,
    calories: 330,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['lighter', 'quick', 'vegetarian', 'summer'],
    ingredients: [i('courgettes', 3, '', 'Fruit & veg'), i('harissa paste', 1, 'tbsp', 'Herbs, spices & sauces'), i('Greek yoghurt', 160, 'g', 'Dairy'), i('lemon', 1, '', 'Fruit & veg'), i('semolina', 25, 'g', 'Carbs'), i('mint', 1, 'bunch', 'Fruit & veg')],
    method: ['Halve courgettes lengthways and score lightly.', 'Rub with harissa and a dusting of semolina.', 'Char in a hot pan, then roast until tender.', 'Spread lemon yoghurt on a plate.', 'Top with courgettes and mint.']
  },
  {
    id: 'twenty-four-hour-pizza-night',
    title: '24-Hour Homemade Pizza Night',
    description: 'Thin homemade pizzas with slow-fermented dough, tomato, cheese and basil.',
    servings: 4,
    protein: 'Vegetarian',
    cuisine: 'Italian',
    timeMinutes: 60,
    calories: 680,
    difficulty: 'Medium',
    familyFriendly: true,
    tags: ['pizza-night', 'fakeaway', 'weekend-cooking', 'family-friendly'],
    ingredients: [i('00 flour', 600, 'g', 'Carbs'), i('water', 390, 'ml', 'Other'), i('yeast', 2, 'g', 'Tins, jars & packets'), i('salt', 14, 'g', 'Herbs, spices & sauces'), i('passata', 250, 'g', 'Tins, jars & packets'), i('mozzarella', 300, 'g', 'Dairy'), i('parmesan', 50, 'g', 'Dairy'), i('basil', 1, 'bunch', 'Fruit & veg')],
    method: ['Mix flour, water, yeast and salt into a dough.', 'Knead until smoother, then cold-ferment for about 24 hours.', 'Ball the dough and bring to room temperature before baking.', 'Top with tomato, mozzarella and parmesan.', 'Bake on a very hot steel and finish with basil.']
  },
  {
    id: 'mediterranean-summer-platter',
    title: 'Mediterranean Summer Sharing Platter',
    description: 'Tomatoes, olives, pan con tomate, charred veg and simple grilled chicken.',
    servings: 4,
    protein: 'Chicken',
    cuisine: 'Mediterranean',
    timeMinutes: 35,
    calories: 610,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['sharing', 'summer', 'high-protein', 'lighter'],
    ingredients: [i('chicken breast', 600, 'g', 'Meat & fish'), i('ciabatta', 1, 'loaf', 'Carbs'), i('tomatoes', 6, '', 'Fruit & veg'), i('olives', 150, 'g', 'Tins, jars & packets'), i('courgettes', 2, '', 'Fruit & veg'), i('basil', 1, 'bunch', 'Fruit & veg'), i('olive oil', 2, 'tbsp', 'Herbs, spices & sauces'), i('garlic', 2, 'cloves', 'Fruit & veg')],
    method: ['Grill seasoned chicken and slice.', 'Toast ciabatta and rub with garlic and tomato.', 'Char courgettes.', 'Arrange tomatoes, olives, basil and chicken on a platter.', 'Drizzle with olive oil and serve.']
  },
  {
    id: 'healthy-fish-taco-bowls',
    title: 'Healthy Fish Taco Bowls',
    description: 'Spiced fish, rice, slaw, lime yoghurt and crunchy vegetables.',
    servings: 4,
    protein: 'Fish',
    cuisine: 'Mexican',
    timeMinutes: 30,
    calories: 520,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['lighter', 'high-protein', 'quick', 'summer'],
    ingredients: [i('white fish fillets', 600, 'g', 'Meat & fish'), i('rice', 280, 'g', 'Carbs'), i('cabbage', 0.5, '', 'Fruit & veg'), i('sweetcorn', 1, 'tin', 'Tins, jars & packets'), i('lime', 2, '', 'Fruit & veg'), i('Greek yoghurt', 150, 'g', 'Dairy'), i('taco seasoning', 2, 'tsp', 'Herbs, spices & sauces')],
    method: ['Cook rice.', 'Season fish with taco spice and bake or pan-fry.', 'Make slaw with cabbage, sweetcorn and lime.', 'Mix yoghurt with lime juice.', 'Serve everything in bowls.']
  },
  {
    id: 'lamb-harissa-flatbreads',
    title: 'Harissa Lamb Flatbreads',
    description: 'Spiced lamb, charred vegetables and yoghurt sauce in warm flatbreads.',
    servings: 4,
    protein: 'Lamb',
    cuisine: 'Middle Eastern',
    timeMinutes: 30,
    calories: 690,
    difficulty: 'Easy',
    familyFriendly: true,
    tags: ['quick', 'high-protein', 'fakeaway', 'spicy'],
    ingredients: [i('lamb mince', 500, 'g', 'Meat & fish'), i('flatbreads', 4, '', 'Carbs'), i('harissa paste', 2, 'tbsp', 'Herbs, spices & sauces'), i('red pepper', 2, '', 'Fruit & veg'), i('red onion', 1, '', 'Fruit & veg'), i('Greek yoghurt', 160, 'g', 'Dairy'), i('mint', 1, 'bunch', 'Fruit & veg')],
    method: ['Fry lamb mince with harissa until browned.', 'Char peppers and onion.', 'Mix yoghurt with mint.', 'Warm flatbreads.', 'Fill with lamb, veg and yoghurt.']
  }
];
