export const recipes = [
  {
    id: 'chicken-fajita-bowls',
    title: 'Chicken Fajita Rice Bowls',
    description: 'Colourful, quick and family-friendly with smoky chicken, peppers and rice.',
    protein: 'Chicken',
    cuisine: 'Mexican',
    timeMinutes: 30,
    calories: 560,
    difficulty: 'Easy',
    familyFriendly: true,
    ingredients: ['chicken breast', 'rice', 'mixed peppers', 'red onion', 'fajita seasoning', 'lime', 'Greek yoghurt'],
    method: ['Cook the rice.', 'Slice chicken, peppers and onion.', 'Fry chicken with fajita seasoning until cooked through.', 'Add peppers and onion and cook until softened but still colourful.', 'Serve over rice with lime and Greek yoghurt.']
  },
  {
    id: 'turkey-meatball-pasta',
    title: 'Turkey Meatball Pasta',
    description: 'Lean turkey meatballs in a rich tomato sauce with pasta.',
    protein: 'Turkey',
    cuisine: 'Italian',
    timeMinutes: 40,
    calories: 620,
    difficulty: 'Medium',
    familyFriendly: true,
    ingredients: ['turkey mince', 'pasta', 'passata', 'garlic', 'onion', 'Italian herbs', 'parmesan'],
    method: ['Mix turkey mince with herbs and shape into meatballs.', 'Brown the meatballs in a pan.', 'Cook onion and garlic, then add passata.', 'Simmer meatballs in the sauce.', 'Serve with pasta and parmesan.']
  },
  {
    id: 'salmon-teriyaki-noodles',
    title: 'Salmon Teriyaki Noodles',
    description: 'Sticky salmon with noodles and crunchy veg.',
    protein: 'Fish',
    cuisine: 'Asian',
    timeMinutes: 25,
    calories: 590,
    difficulty: 'Easy',
    familyFriendly: true,
    ingredients: ['salmon fillets', 'egg noodles', 'soy sauce', 'honey', 'garlic', 'broccoli', 'carrot'],
    method: ['Mix soy sauce, honey and garlic.', 'Pan-fry salmon and glaze with sauce.', 'Cook noodles.', 'Stir-fry broccoli and carrot.', 'Serve salmon over noodles and veg.']
  },
  {
    id: 'beef-chilli',
    title: 'Beef Chilli',
    description: 'A simple chilli con carne that works well for batch cooking.',
    protein: 'Beef',
    cuisine: 'Mexican',
    timeMinutes: 45,
    calories: 650,
    difficulty: 'Easy',
    familyFriendly: true,
    ingredients: ['lean beef mince', 'kidney beans', 'tinned tomatoes', 'onion', 'garlic', 'chilli powder', 'rice'],
    method: ['Brown the beef mince.', 'Add onion and garlic.', 'Stir in chilli powder, tomatoes and beans.', 'Simmer until thick.', 'Serve with rice.']
  },
  {
    id: 'halloumi-flatbreads',
    title: 'Halloumi Flatbreads',
    description: 'Charred halloumi, salad and yoghurt sauce in warm flatbreads.',
    protein: 'Vegetarian',
    cuisine: 'Mediterranean',
    timeMinutes: 20,
    calories: 540,
    difficulty: 'Easy',
    familyFriendly: true,
    ingredients: ['halloumi', 'flatbreads', 'lettuce', 'tomatoes', 'cucumber', 'Greek yoghurt', 'lemon'],
    method: ['Slice and grill halloumi.', 'Mix yoghurt with lemon.', 'Warm flatbreads.', 'Fill with salad, halloumi and sauce.']
  },
  {
    id: 'chicken-caesar-wraps',
    title: 'Chicken Caesar Wraps',
    description: 'A lighter Caesar-style chicken wrap for busy evenings.',
    protein: 'Chicken',
    cuisine: 'British',
    timeMinutes: 20,
    calories: 500,
    difficulty: 'Easy',
    familyFriendly: true,
    ingredients: ['cooked chicken', 'wraps', 'romaine lettuce', 'Greek yoghurt', 'parmesan', 'lemon', 'garlic'],
    method: ['Mix yoghurt, parmesan, lemon and garlic.', 'Slice chicken.', 'Fill wraps with lettuce, chicken and sauce.', 'Toast lightly if preferred.']
  },
  {
    id: 'pork-stir-fry',
    title: 'Pork Stir-Fry with Rice',
    description: 'Fast pork strips with vegetables and a sticky soy glaze.',
    protein: 'Pork',
    cuisine: 'Asian',
    timeMinutes: 25,
    calories: 580,
    difficulty: 'Easy',
    familyFriendly: true,
    ingredients: ['pork loin steaks', 'rice', 'mixed stir-fry vegetables', 'soy sauce', 'honey', 'ginger', 'garlic'],
    method: ['Cook the rice.', 'Slice pork thinly.', 'Stir-fry pork until browned.', 'Add vegetables, soy, honey, ginger and garlic.', 'Serve with rice.']
  },
  {
    id: 'lentil-bolognese',
    title: 'Lentil Bolognese',
    description: 'A cheap, filling vegetarian pasta sauce.',
    protein: 'Vegetarian',
    cuisine: 'Italian',
    timeMinutes: 35,
    calories: 520,
    difficulty: 'Easy',
    familyFriendly: true,
    ingredients: ['red lentils', 'pasta', 'passata', 'onion', 'carrot', 'celery', 'Italian herbs'],
    method: ['Soften onion, carrot and celery.', 'Add lentils, passata and herbs.', 'Simmer until lentils are soft.', 'Serve with pasta.']
  },
  {
    id: 'lamb-kofta-plates',
    title: 'Lamb Kofta Plates',
    description: 'Spiced lamb koftas with couscous and salad.',
    protein: 'Lamb',
    cuisine: 'Mediterranean',
    timeMinutes: 35,
    calories: 680,
    difficulty: 'Medium',
    familyFriendly: true,
    ingredients: ['lamb mince', 'couscous', 'cucumber', 'tomatoes', 'Greek yoghurt', 'mint', 'cumin'],
    method: ['Mix lamb mince with cumin and mint.', 'Shape into koftas.', 'Grill or fry until cooked.', 'Prepare couscous and salad.', 'Serve with yoghurt.']
  },
  {
    id: 'fish-tacos',
    title: 'Crispy Fish Tacos',
    description: 'Crispy white fish with crunchy slaw and lime yoghurt.',
    protein: 'Fish',
    cuisine: 'Mexican',
    timeMinutes: 30,
    calories: 570,
    difficulty: 'Medium',
    familyFriendly: true,
    ingredients: ['white fish fillets', 'tortillas', 'cabbage', 'carrot', 'lime', 'Greek yoghurt', 'paprika'],
    method: ['Season fish with paprika.', 'Bake or pan-fry until crisp.', 'Make slaw with cabbage, carrot and lime.', 'Fill tortillas with fish, slaw and yoghurt.']
  },
  {
    id: 'sausage-traybake',
    title: 'Sausage and Veg Traybake',
    description: 'Simple one-tray dinner with sausages, potatoes and vegetables.',
    protein: 'Pork',
    cuisine: 'British',
    timeMinutes: 50,
    calories: 700,
    difficulty: 'Easy',
    familyFriendly: true,
    ingredients: ['sausages', 'baby potatoes', 'red onion', 'carrots', 'courgette', 'olive oil', 'rosemary'],
    method: ['Chop potatoes and vegetables.', 'Add to a roasting tray with sausages.', 'Season with rosemary and a little oil.', 'Roast until golden and cooked through.']
  },
  {
    id: 'chicken-tikka-naan',
    title: 'Chicken Tikka Naan Plates',
    description: 'Tikka-style chicken with naan, salad and yoghurt.',
    protein: 'Chicken',
    cuisine: 'Indian',
    timeMinutes: 35,
    calories: 640,
    difficulty: 'Easy',
    familyFriendly: true,
    ingredients: ['chicken thighs', 'tikka paste', 'naan breads', 'lettuce', 'cucumber', 'Greek yoghurt', 'mango chutney'],
    method: ['Coat chicken in tikka paste.', 'Roast or grill until cooked.', 'Warm naan breads.', 'Serve with salad, yoghurt and chutney.']
  },
  {
    id: 'egg-fried-rice',
    title: 'Egg Fried Rice with Peas',
    description: 'A quick vegetarian rice dinner with eggs and vegetables.',
    protein: 'Vegetarian',
    cuisine: 'Asian',
    timeMinutes: 18,
    calories: 480,
    difficulty: 'Easy',
    familyFriendly: true,
    ingredients: ['cooked rice', 'eggs', 'peas', 'spring onions', 'soy sauce', 'sesame oil', 'carrot'],
    method: ['Scramble eggs in a hot pan.', 'Add cooked rice and vegetables.', 'Stir-fry with soy sauce and sesame oil.', 'Finish with spring onions.']
  },
  {
    id: 'beef-burger-bowls',
    title: 'Beef Burger Bowls',
    description: 'Burger flavours without the bun, served with wedges and salad.',
    protein: 'Beef',
    cuisine: 'American',
    timeMinutes: 35,
    calories: 660,
    difficulty: 'Easy',
    familyFriendly: true,
    ingredients: ['lean beef mince', 'potatoes', 'lettuce', 'tomatoes', 'gherkins', 'cheddar', 'burger sauce'],
    method: ['Bake potato wedges.', 'Brown beef mince and season.', 'Build bowls with lettuce, tomatoes, gherkins and beef.', 'Top with cheddar and burger sauce.']
  },
  {
    id: 'prawn-linguine',
    title: 'Garlic Prawn Linguine',
    description: 'Light pasta with prawns, garlic, lemon and chilli.',
    protein: 'Fish',
    cuisine: 'Italian',
    timeMinutes: 22,
    calories: 530,
    difficulty: 'Easy',
    familyFriendly: true,
    ingredients: ['prawns', 'linguine', 'garlic', 'lemon', 'chilli flakes', 'parsley', 'cherry tomatoes'],
    method: ['Cook linguine.', 'Fry garlic, tomatoes and prawns.', 'Add lemon and chilli.', 'Toss with pasta and parsley.']
  },
  {
    id: 'chicken-noodle-soup',
    title: 'Chicken Noodle Soup',
    description: 'Comforting broth with chicken, noodles and vegetables.',
    protein: 'Chicken',
    cuisine: 'Asian',
    timeMinutes: 30,
    calories: 460,
    difficulty: 'Easy',
    familyFriendly: true,
    ingredients: ['chicken thighs', 'chicken stock', 'noodles', 'carrot', 'spring onions', 'soy sauce', 'ginger'],
    method: ['Simmer chicken in stock with ginger.', 'Shred cooked chicken.', 'Add noodles, carrot and soy sauce.', 'Finish with spring onions.']
  },
  {
    id: 'sweet-potato-curry',
    title: 'Sweet Potato Chickpea Curry',
    description: 'Mild, filling vegetarian curry.',
    protein: 'Vegetarian',
    cuisine: 'Indian',
    timeMinutes: 40,
    calories: 560,
    difficulty: 'Easy',
    familyFriendly: true,
    ingredients: ['sweet potato', 'chickpeas', 'coconut milk', 'curry powder', 'spinach', 'rice', 'onion'],
    method: ['Cook onion with curry powder.', 'Add sweet potato, chickpeas and coconut milk.', 'Simmer until tender.', 'Stir in spinach and serve with rice.']
  },
  {
    id: 'bbq-chicken-potatoes',
    title: 'BBQ Chicken Loaded Potatoes',
    description: 'Baked potatoes topped with BBQ chicken and salad.',
    protein: 'Chicken',
    cuisine: 'American',
    timeMinutes: 50,
    calories: 620,
    difficulty: 'Easy',
    familyFriendly: true,
    ingredients: ['baking potatoes', 'cooked chicken', 'BBQ sauce', 'sweetcorn', 'lettuce', 'cheddar', 'spring onions'],
    method: ['Bake potatoes until soft.', 'Warm chicken with BBQ sauce.', 'Split potatoes and top with chicken.', 'Add sweetcorn, cheddar, lettuce and spring onions.']
  },
  {
    id: 'tuna-pasta-bake',
    title: 'Tuna Pasta Bake',
    description: 'Classic family pasta bake with tuna, tomato and cheese.',
    protein: 'Fish',
    cuisine: 'British',
    timeMinutes: 45,
    calories: 640,
    difficulty: 'Easy',
    familyFriendly: true,
    ingredients: ['tuna', 'pasta', 'passata', 'sweetcorn', 'cheddar', 'onion', 'garlic'],
    method: ['Cook pasta.', 'Make tomato sauce with onion, garlic and passata.', 'Stir in tuna and sweetcorn.', 'Top with cheddar and bake until bubbling.']
  },
  {
    id: 'steak-flatbread-salad',
    title: 'Steak Flatbread Salad',
    description: 'Sliced steak, salad and yoghurt dressing on warm flatbreads.',
    protein: 'Beef',
    cuisine: 'Mediterranean',
    timeMinutes: 25,
    calories: 610,
    difficulty: 'Medium',
    familyFriendly: true,
    ingredients: ['steak', 'flatbreads', 'rocket', 'tomatoes', 'red onion', 'Greek yoghurt', 'lemon'],
    method: ['Cook steak to your liking and rest it.', 'Warm flatbreads.', 'Mix yoghurt with lemon.', 'Slice steak and serve with salad on flatbreads.']
  }
];
